# Configuração para IDEs - Sistema OCR NR-13

[tool.pyright]
include = ["."]
exclude = ["venv", "env", ".venv", "__pycache__"]
stubPath = ""
venvPath = ""
venv = ""

[tool.pylsp-mypy]
enabled = true
live_mode = true

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

# Ignora warnings para módulos locais
[[tool.mypy.overrides]]
module = [
    "config.*",
    "ocr.*", 
    "services",
    "utils"
]
ignore_missing_imports = true
ignore_errors = true
